// Manage embedded bash scripts.
//
// `lib/embedded.gen.js` is generated by `scripts/build-embed.mjs` before
// esbuild runs. It exports `EMBEDDED_SOURCES` — an object of
// { 'doctor.sh': '<utf8 body>', ... }. The generated file is committed so
// `node bin/vibe-code-tours.mjs` works without a build step.
//
// At runtime we materialize the scripts into ~/.vct/scripts/<name>.sh with
// mode 0755 and re-extract if the on-disk copy drifts from the embedded
// copy (SHA-256 compare).

import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { ensureVctDir } from './config.js';
import { EMBEDDED_SOURCES } from './embedded.gen.js';

export const SCRIPT_FILES = ['doctor.sh', 'student-setup.sh', 'api-setup.sh', 'check-ch1.sh'];

function sha256(buf) {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

export const EMBEDDED = Object.fromEntries(
  SCRIPT_FILES.map((name) => {
    const src = EMBEDDED_SOURCES[name];
    if (typeof src !== 'string') {
      throw new Error(`Embedded source missing for ${name} — re-run scripts/build-embed.mjs`);
    }
    const body = Buffer.from(src, 'utf8');
    return [name, { body, sha256: sha256(body) }];
  }),
);

export async function materializeScripts(home = os.homedir()) {
  await ensureVctDir(home);
  const targetDir = path.join(home, '.vct', 'scripts');
  const written = [];
  for (const name of SCRIPT_FILES) {
    const target = path.join(targetDir, name);
    const embedded = EMBEDDED[name];
    let needsWrite = true;
    try {
      const onDisk = await fs.readFile(target);
      if (sha256(onDisk) === embedded.sha256) needsWrite = false;
    } catch (err) {
      if (err.code !== 'ENOENT') throw err;
    }
    if (needsWrite || process.env.VCT_FORCE_EXTRACT === '1') {
      const tmp = `${target}.tmp-${process.pid}`;
      await fs.writeFile(tmp, embedded.body, { mode: 0o755 });
      await fs.rename(tmp, target);
      await fs.chmod(target, 0o755);
      written.push(name);
    }
  }
  return { dir: targetDir, written };
}

export function getScriptPath(name, home = os.homedir()) {
  if (!SCRIPT_FILES.includes(name)) {
    throw new Error(`Unknown script: ${name}`);
  }
  return path.join(home, '.vct', 'scripts', name);
}

export async function verifyScript(name, home = os.homedir()) {
  const target = getScriptPath(name, home);
  const onDisk = await fs.readFile(target);
  const expected = EMBEDDED[name].sha256;
  const actual = sha256(onDisk);
  if (actual !== expected) {
    throw new Error(`Checksum mismatch for ${name}: expected ${expected.slice(0, 12)}…, got ${actual.slice(0, 12)}…`);
  }
  return true;
}
