#!/usr/bin/env node
// Generates lib/embedded.gen.js from scripts/*.sh. Run before esbuild.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..');
const SCRIPTS_DIR = path.join(REPO, 'scripts');
const OUT = path.join(REPO, 'lib', 'embedded.gen.js');

const FILES = ['doctor.sh', 'student-setup.sh', 'api-setup.sh', 'check-ch1.sh'];

async function main() {
  const entries = {};
  for (const name of FILES) {
    const body = await fs.readFile(path.join(SCRIPTS_DIR, name), 'utf8');
    entries[name] = body;
  }
  const header = `// AUTO-GENERATED by scripts/build-embed.mjs — do not edit by hand.
// Regenerate via: node scripts/build-embed.mjs
// Sources: scripts/{${FILES.join(',')}}
`;
  const body = `export const EMBEDDED_SOURCES = ${JSON.stringify(entries, null, 2)};\n`;
  await fs.writeFile(OUT, header + body, 'utf8');
  const size = (await fs.stat(OUT)).size;
  process.stdout.write(`wrote ${path.relative(REPO, OUT)} (${(size / 1024).toFixed(1)} KB, ${FILES.length} scripts)\n`);
}

main().catch((err) => {
  process.stderr.write(`build-embed failed: ${err.message}\n`);
  process.exit(1);
});
