#!/usr/bin/env node
// Generates lib/embedded.gen.js from scripts/{*.sh,guides/*,chapters/*,faq/*}.
// Run before esbuild.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..');
const SCRIPTS_DIR = path.join(REPO, 'scripts');
const OUT = path.join(REPO, 'lib', 'embedded.gen.js');

const SHELL_FILES = ['doctor.sh', 'student-setup.sh', 'api-setup.sh', 'check-ch1.sh'];

async function listIfExists(dir) {
  try {
    const items = await fs.readdir(dir);
    return items.filter((n) => !n.startsWith('.'));
  } catch (err) {
    if (err.code === 'ENOENT') return [];
    throw err;
  }
}

async function readDir(rel) {
  const dir = path.join(SCRIPTS_DIR, rel);
  const names = await listIfExists(dir);
  const out = {};
  for (const name of names.sort()) {
    out[name] = await fs.readFile(path.join(dir, name), 'utf8');
  }
  return out;
}

async function main() {
  const shells = {};
  for (const name of SHELL_FILES) {
    shells[name] = await fs.readFile(path.join(SCRIPTS_DIR, name), 'utf8');
  }
  // Also probe for additional check-ch*.sh siblings vendored later.
  const all = await listIfExists(SCRIPTS_DIR);
  for (const n of all) {
    if (/^check-ch\d+\.sh$/.test(n) && !shells[n]) {
      shells[n] = await fs.readFile(path.join(SCRIPTS_DIR, n), 'utf8');
    }
  }

  const guides = await readDir('guides');
  const chapters = await readDir('chapters');
  const faq = await readDir('faq');

  const header = `// AUTO-GENERATED by scripts/build-embed.mjs — do not edit by hand.
// Regenerate via: node scripts/build-embed.mjs
// Includes: shell scripts, guides/, chapters/, faq/.
`;
  const body =
    `export const EMBEDDED_SOURCES = ${JSON.stringify(shells, null, 2)};\n` +
    `export const EMBEDDED_GUIDES = ${JSON.stringify(guides, null, 2)};\n` +
    `export const EMBEDDED_CHAPTERS = ${JSON.stringify(chapters, null, 2)};\n` +
    `export const EMBEDDED_FAQ = ${JSON.stringify(faq, null, 2)};\n`;
  await fs.writeFile(OUT, header + body, 'utf8');
  const size = (await fs.stat(OUT)).size;
  const counts = {
    shells: Object.keys(shells).length,
    guides: Object.keys(guides).length,
    chapters: Object.keys(chapters).length,
    faq: Object.keys(faq).length,
  };
  process.stdout.write(
    `wrote ${path.relative(REPO, OUT)} (${(size / 1024).toFixed(1)} KB; ` +
      `${counts.shells} shells, ${counts.guides} guides, ${counts.chapters} chapters, ${counts.faq} faq)\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`build-embed failed: ${err.message}\n`);
  process.exit(1);
});
